### PR TITLE
create Friendship model, add user methods, create migrations

### PR DESCRIPTION
**Pull request by RokoVarano**
We have created the Friendship model, along with the corresponding migrations and user methods

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: INVALID :red_circle: 

**Hi @RokoVarano and @JohnHernCode **
There are migration issue on my system due to `20200204165841_remove_foreign_keys.rb` and `20200204045301_create_likes.rb`. Please Fix them andSubmit another request for review. 
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi team!
Great job so far on this milestone:clap::clap:.**

**Major highlights**
- The associations between user and friendship were rightly done using the correct has_many and  belong_to relationships.
- Logged-in users can easily create a post.

However, we still need to make a few changes to get the project approved:muscle:.

**To improve**
- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, there's no button to invite a user to friendship. Kindly add it.

- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). This feature is also missing. Please add it.

- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also add this feature.

- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Add this feature. It's also currently missing.

- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, the post timeline displays the posts of all logged-in users. Instead of their friends. Kindly fix this.

- [x] There are currently no tests. Kindly write tests for the features already implemented in the app. Both unit and integration test that covers positive and negative test case scenarios.

- [x] Move the logic in application.html.erb in view to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) on how to use a helper in rails. see [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright.

- [x] Kindly add the names of the author to the readme.

 [ Optional]
- Kindly display the name of the logged-in user on the navbar. This will enable us to easily identify the current user from other users. 

Make the above-required changes and when you are ready, request another review.
Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @RokoVarano and @JohnHernCode, Both of you have done remarkably well on this project.
I am impressed with your work
* Clean codebase 👍 
* Great use of helpers to keep logic out of your views 👏 
* Maintained a good MVC pattern good practice. Made sure all your business logic remain in model. 👏 
* Great tests coverage 👏 

Let us quickly add some finishing touches and request another review.

- [x] Currently the post of current user's friend repeats, kind fix this. Same with "my friends" page

- [x] Your ReadMe file still carries the app template description. "This repo includes initial code for social media app with basic styling. Its purpose is to be a starting point for Microverse students." I am sure you will agree with me, this repo no longer carries initial code, you have done a lot. Do well to update it to reflect what the app is all about. Possibly a screenshot too, to give it that professional look. This too "Tests will be added by Microverse students. There are no tests for initial features in order to make sure that students write all tests from scratch."


- [x] From henceforth, ensure that your commit messages are capitalized. You can watch this [video](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6) on how to edit your commit messages using git rebase. See [Git Commit Best Practices](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) for more insights. 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: :1st_place_medal: 
---------------
Hello, @RokoVarano  @JohnHernCode  you did an amazing job in this project. Great job working on the required changes. :muscle: . 
---------------
Now you can merge this branch :smile: 
Reachme on SLACK if you have any questions. 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!! AND GOOD LUCK WITH THE NEXT MILESTONES.

**Pull request merged**
